import { ArticleProps } from "@/types/index";

export const dataTestCategories: string[] = [
  "tout",
  "technologie",
  "electro-menager",
  "nourriture",
  "vetement",
  "jouet",
];

export const dataTestArticles: ArticleProps[] = [
  {
    _id: "article-1",
    createdAt: "2024-04-04",
    updatedAt: "2024-04-04",
    archive: false,
    name: "ADATA SSD Go",
    images: ["1.jpg", "1.jpg", "1.jpg"],
    description:
      "no more Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio beatae quas et labore, fugiat voluptas tempore iste, repellat inventore, commodi corrupti excepturi harum? Laboriosam odio soluta alias quod iusto porro.",
    category: "technologies",
    tags: ["pc composant", "hard drive"],
    price: 20000,
    quatity: 8,
    discount: 10,
    likes: ["user-1"],
    ratings: [
      { user: "user-1", note: 2 },
      { user: "user-2", note: 5 },
      { user: "user-3", note: 4 },
      { user: "user-4", note: 7 },
      { user: "user-5", note: 3 },
    ],
  },
  {
    _id: "article-2",
    createdAt: "2024-04-04",
    updatedAt: "2024-04-04",
    archive: false,
    name: "ADATA SSD Go",
    images: ["2.jpg"],
    description:
      "no more Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio beatae quas et labore, fugiat voluptas tempore iste, repellat inventore, commodi corrupti excepturi harum? Laboriosam odio soluta alias quod iusto porro.",
    category: "technologies",
    tags: ["pc composant", "hard drive"],
    price: 20000,
    quatity: 8,
    discount: 0,
    likes: ["user-1"],
    ratings: [
      { user: "user-1", note: 2 },
      { user: "user-2", note: 5 },
      { user: "user-3", note: 4 },
      { user: "user-4", note: 7 },
      { user: "user-5", note: 3 },
    ],
  },
  {
    _id: "article-3",
    createdAt: "2024-04-04",
    updatedAt: "2024-04-04",
    archive: false,
    name: "ADATA SSD Go",
    images: ["3.jpg"],
    description:
      "no more Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio beatae quas et labore, fugiat voluptas tempore iste, repellat inventore, commodi corrupti excepturi harum? Laboriosam odio soluta alias quod iusto porro.",
    category: "technologies",
    tags: ["pc composant", "hard drive"],
    price: 20000,
    quatity: 8,
    discount: 0,
    likes: ["user-1"],
    ratings: [
      { user: "user-1", note: 2 },
      { user: "user-2", note: 5 },
      { user: "user-3", note: 4 },
      { user: "user-4", note: 7 },
      { user: "user-5", note: 3 },
    ],
  },
  {
    _id: "article-2",
    createdAt: "2024-04-04",
    updatedAt: "2024-04-04",
    archive: false,
    name: "ADATA SSD Go",
    images: ["4.jpg"],
    description:
      "no more Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio beatae quas et labore, fugiat voluptas tempore iste, repellat inventore, commodi corrupti excepturi harum? Laboriosam odio soluta alias quod iusto porro.",
    category: "technologies",
    tags: ["pc composant", "hard drive"],
    price: 20000,
    quatity: 8,
    discount: 20,
    likes: ["user-1"],
    ratings: [
      { user: "user-1", note: 2 },
      { user: "user-2", note: 5 },
      { user: "user-3", note: 4 },
      { user: "user-4", note: 7 },
      { user: "user-5", note: 3 },
    ],
  },
  {
    _id: "article-5",
    createdAt: "2024-04-04",
    updatedAt: "2024-04-04",
    archive: false,
    name: "ADATA SSD Go",
    images: ["5.jpg"],
    description:
      "no more Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio beatae quas et labore, fugiat voluptas tempore iste, repellat inventore, commodi corrupti excepturi harum? Laboriosam odio soluta alias quod iusto porro.",
    category: "technologies",
    tags: ["pc composant", "hard drive"],
    price: 20000,
    quatity: 8,
    discount: 10,
    likes: ["user-1"],
    ratings: [
      { user: "user-1", note: 2 },
      { user: "user-2", note: 5 },
      { user: "user-3", note: 4 },
      { user: "user-4", note: 7 },
      { user: "user-5", note: 3 },
    ],
  },
  {
    _id: "article-6",
    createdAt: "2024-04-04",
    updatedAt: "2024-04-04",
    archive: false,
    name: "Sweat blanc",
    images: ["6.png"],
    description:
      "no more Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio beatae quas et labore, fugiat voluptas tempore iste, repellat inventore, commodi corrupti excepturi harum? Laboriosam odio soluta alias quod iusto porro.",
    category: "vetements",
    tags: ["pc composant", "hard drive"],
    price: 20000,
    quatity: 8,
    discount: 10,
    likes: ["user-1"],
    ratings: [
      { user: "user-1", note: 2 },
      { user: "user-2", note: 5 },
      { user: "user-3", note: 4 },
      { user: "user-4", note: 7 },
      { user: "user-5", note: 3 },
    ],
  },
];
